apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
        - name: simple-time-service-container
          image: priyanshushriv/simpletimeservice
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-time-service-service
spec:
  type: NodePort
  selector:
    app: simple-time-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000